[test]
coverageSkipTestFiles = true
coverageThreshold = { lines = 0.9, functions = 0.8, statements = 0.85 }
coverageIgnoreSourcemaps = true
coverageReporter  = ["text", "lcov"]
coverageDir = "./coverage"